package com.bnpparibas.dao;

import com.bnpparibas.model.ImportStats;
import com.bnpparibas.util.HibernateUtil;

import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.query.Query;

import java.util.List;

public class ImportStatsDAO {

    /**
     * Save one import result (one file import)
     */
    public Long recordImport(String username, int valid, int invalid) {

        if (username == null || username.trim().isEmpty()) {
            System.err.println("[ImportStatsDAO] Username is missing");
            return null;
        }

        Session session = null;
        Transaction tx = null;

        try {
            session = HibernateUtil.getSessionFactory().openSession();
            tx = session.beginTransaction();

            // create object
            ImportStats stats = new ImportStats();
            stats.setUsername(username);
            stats.setFilesImported(1); // one file per import
            stats.setTotalValid(valid);
            stats.setTotalInvalid(invalid);

            // save → ID auto generated by DB
            session.save(stats);

            tx.commit();

            // return generated ID
            return stats.getId();

        } catch (Exception e) {
            if (tx != null) tx.rollback();
            System.err.println("[ImportStatsDAO] Error while saving import stats");
            e.printStackTrace();
            return null;

        } finally {
            if (session != null) session.close();
        }
    }

    /**
     * Print all import stats (for debugging)
     */
    public void printAllImports() {

        Session session = null;

        try {
            session = HibernateUtil.getSessionFactory().openSession();

            Query<ImportStats> query =
                    session.createQuery("FROM ImportStats", ImportStats.class);

            List<ImportStats> list = query.list();

            System.out.println("\n===== IMPORT STATS =====");

            for (ImportStats s : list) {
                System.out.printf(
                        "%d | %s | %d | %d | %d%n",
                        s.getId(),
                        s.getUsername(),
                        s.getFilesImported(),
                        s.getTotalValid(),
                        s.getTotalInvalid()
                );
            }

            System.out.println("===== END =====\n");

        } catch (Exception e) {
            System.err.println("[ImportStatsDAO] Error fetching stats");
            e.printStackTrace();

        } finally {
            if (session != null) session.close();
        }
    }
}